### ISSUE TITLE
Asset organization or lack thereof

### ISSUE THREAD

**Issue by FaderKing** [Sporadica-IS/Sporadica-IS.github.io#4]
### WTAF?!
Well I have no puns when I say that the [Front-end](https://github.com/Sporadica-IS/Sporadica-IS.github.io/tree/Front-end) branch looks like absolute chaos. 
If I remember correctly, the first changes I pushed to that branch were mostly centered around organizing the website content, code and media alike. The css, js & img folders were made specifically for that purpose. I actually thought that would set way for a means of storing all our content, I was even expecting to maybe see a couple of new folders for stuff like videos or something, you can imagine my surprise to see images right in the main directory of the repository and even find stuff like embedded [js](https://github.com/Sporadica-IS/Sporadica-IS.github.io/blame/Front-end/SYNT%CE%94KT%C3%8EK.html#L204-#L225) code and [css](https://github.com/Sporadica-IS/Sporadica-IS.github.io/blame/Front-end/SYNT%CE%94KT%C3%8EK.html#L30-L97) styling in some HTML files. I don't want to be *that* guy but please fix this, anyone looking at that code base (which *is* **public** btw) will think that it was written by a noob.

Please fix this abeg

**Comment by Tamunokorite** [comment]
Yeah, I'm working on that too

**Comment by FaderKing** [comment]
> Yeah, I'm working on that too

Noice, looking forward to seeing that

**Comment by GamerDTK** [comment]
Interesting

**Comment by GamerDTK** [comment]
So this is for the webpage or something?

**Comment by GamerDTK** [comment]
See jamb question 🤦‍♂️

**Comment by blvckfire** [comment]
God help you guys lol

**Comment by fortune710** [comment]
I'm just seeing this sorry 
We'll work on it

**Comment by FaderKing** [comment]
Great Job peeps, y'all cleaned it up pretty quickly
